{% set name = "pixsfm" %}
{% set version = "1.0.0" %}
{% set build = 5 %}

{% set processor = "cpu" if cuda_compiler_version == "None" else "gpu" %}  # [not osx]
{% set processor = "cpu" %}  # [osx]

# Prioritize gpu build if cudatoolkit can be installed (through __cuda virtual package)
{% set build = build + 100 if processor == "gpu" else build %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cvg/pixel-perfect-sfm/archive/refs/tags/v{{ version.split('.')[0] }}.{{ version.split('.')[1] }}.tar.gz
  sha256: 0b24a8b90ec1aeac4f8e2df211f1604d585c7f3a71be4626bb6750b020b5ad1b
  patches:
    - unvendor.patch
    - limit-parallel-jobs.patch
    - fix-osx.patch  # [osx]
    - 119.patch
    - fix-python-executable.patch

build:
  number: {{ build }}
  string: {{ processor }}h{{ PKG_HASH }}_{{ build }}
  skip: True  # [win]
  skip: True  # [py<39]
  script: ${PYTHON} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}         # [(cuda_compiler or "None") != "None"]
    - cmake
    - make
    - git
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    # x11 stuff
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxcb') }}            # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxfixes') }}         # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]
    - {{ cdt('libxau') }}            # [linux]
    - {{ cdt('expat-devel') }}       # [linux]
    - sysroot_linux-64 2.17          # [linux64]
  host:
    - hdf5
    - pybind11
    - highfive
    - cpp-half
    - python
    - pip
    - eigen
    - cgal-cpp
    - colmap =3.8={{ processor }}*
    - ceres-solver
    - highfive
    - numpy
    - pycolmap =*=cuda*  # [(cuda_compiler or "None") != "None"]
    - pycolmap =*=cpu*   # [(cuda_compiler or "None") == "None"]
    - pyceres
    - pytorch
    - torchvision
    - libboost-devel
    - glog
    - gflags
    - libcurand-dev                  # [cuda_compiler_version == "12.0"]
    - cuda-cudart-dev                # [win and cuda_compiler_version == "12.0"]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pycolmap
    - pyceres
    - tqdm
    - matplotlib-base
    - plotly
    - scipy
    - h5py
    - omegaconf
    - packaging
    - hloc
    - setuptools
    - __cuda >={{ cuda_compiler_version }}  # [(cuda_compiler or "None") != "None"]


test:
  imports:
    - pixsfm
    - pixsfm.refine_colmap
    - pixsfm.refine_hloc

about:
  home: https://github.com/cvg/pixel-perfect-sfm
  license: Apache-2.0
  license_file: LICENSE
  summary: Pixel-Perfect Structure-from-Motion
  description: | 
    Here we provide pixsfm, a Python package that can be readily used with COLMAP and our toolbox hloc.
    This makes it easy to refine an existing COLMAP model or reconstruct a new dataset with state-of-the-art
    image matching. Our framework also improves visual localization in challenging conditions.

extra:
  recipe-maintainers:
    - Tobias-Fischer
