azure:
  free_disk_space: true
  settings_linux:
    swapfile_size: 4GiB
  # Workaround for https://github.com/conda-forge/opencv-feedstock/issues/493
  settings_osx:
    pool:
      vmImage: macos-14
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native
